# NumPy

In [272]:
import numpy as np

In [273]:
#Arange

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [274]:
#zeros

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [275]:
#ones

np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [276]:
#linspace

np.linspace(0,20,50)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [277]:
#eye

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [278]:
#random.rand

np.random.rand(10)

array([0.46304889, 0.97952336, 0.79451247, 0.11936253, 0.11082828,
       0.88849387, 0.52834595, 0.53573088, 0.82869346, 0.84863679])

In [279]:
#random.randn

np.random.randn(10)

array([ 1.24891857, -0.79010008, -1.12588124,  1.43227177, -0.61744569,
       -0.30881877,  1.07439996, -1.13653169, -1.79040929,  0.01162801])

In [280]:
#random.randint

np.random.randint(101)

72

In [281]:
#array

np.array([1,2,3])

array([1, 2, 3])

In [282]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [283]:
np.random.uniform(5,10,size = 4)

array([9.63100845, 6.33402772, 5.71715076, 9.24772518])

In [284]:
np.random.random(3)

array([0.44276198, 0.06707678, 0.92450031])

In [285]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [286]:
arr = np.array([16,91,20,3,83,49,45,6,60,12])
arr.min()

3

In [287]:
arr.max()

91

In [288]:
arr.shape

(10,)

In [289]:
arr.argmin()

3

In [290]:
arr.argmax()

1

In [291]:
np.sort(arr)

array([ 3,  6, 12, 16, 20, 45, 49, 60, 83, 91])

In [292]:
#np.setdiff1d function returns all the unique elements from array 1 that are not present in arr2.

a = np.array([1, 7, 3, 2, 4, 1])
b = np.array([9, 2, 5, 6, 7, 8])
np.setdiff1d(a, b)

array([1, 3, 4])

In [293]:
#setxor1dfunction will return all the unique values from both arrays in sorted order.

a = np.array([1, 2, 3, 4, 6])
b = np.array([1, 4, 9, 4, 36])
np.setxor1d(a,b)

array([ 2,  3,  6,  9, 36])

# Pandas

In [294]:
import pandas as pd

In [295]:
s = pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])
s[:2]

a    3
b   -5
dtype: int64

In [296]:
#Drops values from rows

s.drop(['a', 'c'])

b   -5
d    4
dtype: int64

In [297]:
#Substracts a value from the series

s.sub(2)

a    1
b   -7
c    5
d    2
dtype: int64

In [298]:
#Adds a value to the series

s.add(2)

a    5
b   -3
c    9
d    6
dtype: int64

In [299]:
#Multiplies a value to the series

s.mul(2)

a     6
b   -10
c    14
d     8
dtype: int64

In [300]:
#Devides a value from the series

s.div(2)

a    1.5
b   -2.5
c    3.5
d    2.0
dtype: float64

In [301]:
#Index minimum

s.idxmin()

'b'

In [302]:
#Index maximum

s.idxmax()

'c'

In [303]:
dict = {'Name':["Bola", "Joy", "Grace", "Amaka"], 
        'Degree': ["BSc", "MSc", "FSLC", "PhD"], 
        'ID':[20, 12, 32, 14]} 
   
df = pd.DataFrame(dict, index = [True, False, True, False]) 
   
print(df) 

        Name Degree  ID
True    Bola    BSc  20
False    Joy    MSc  12
True   Grace   FSLC  32
False  Amaka    PhD  14


In [304]:
#Count colums

df.count()

Name      4
Degree    4
ID        4
dtype: int64

In [305]:
#Get information on dataframe

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, True to False
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Degree  4 non-null      object
 2   ID      4 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 128.0+ bytes


In [306]:
#Retrieves index description

df.index

Index([True, False, True, False], dtype='object')

In [307]:
#Describe colums of dataframe

df.columns

Index(['Name', 'Degree', 'ID'], dtype='object')

In [308]:
df.rank()

Name  Degree   ID
True    2.0     1.0  3.0
False   4.0     3.0  1.0
True    3.0     2.0  4.0
False   1.0     4.0  2.0

In [309]:
df.describe()

ID
count   4.0
mean   19.5
std     9.0
min    12.0
25%    13.5
50%    17.0
75%    23.0
max    32.0

In [310]:
df.min()

Name      Amaka
Degree      BSc
ID           12
dtype: object

In [311]:
df.max()

Name      Joy
Degree    PhD
ID         32
dtype: object

In [312]:
#Drop values from colums

df.drop('ID', axis=1)

Name Degree
True    Bola    BSc
False    Joy    MSc
True   Grace   FSLC
False  Amaka    PhD

In [313]:
#Rename colums in dataframe

df.columns = ['Name', 'Degree', 'Personal_ID']
df

Name Degree  Personal_ID
True    Bola    BSc           20
False    Joy    MSc           12
True   Grace   FSLC           32
False  Amaka    PhD           14

In [314]:
len(df)

4

In [315]:
df.dtypes

Name           object
Degree         object
Personal_ID     int64
dtype: object